version: 2.1
setup: false
orbs:
  aws-ecs: circleci/aws-ecs@3.2.0
  aws-ecr: circleci/aws-ecr@8.1.2
  node: circleci/node@5.0.2
  docker: circleci/docker@1.5.0
jobs:
  test:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - checkout
      - run:
            name: npm
            command: |
              npm i
      - run: 
          name: test
          command: |
              export NODE_ENV=development && node_modules/.bin/mocha --reporter mochawesome --reporter-options reportDir=test-results,reportFilename=test-results --timeout 30000 --exit
      - run:
            name: fail
            command: |
              curl -X POST -H 'Content-type: application/json' --data "{'text':'pipeline fail'}" https://hooks.slack.com/services/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
            when: on_fail
workflows:
  test-build-deploy:
    jobs:
      - test
      - aws-ecr/build-and-push-image: # Use the pre-defined `build-and-push-image` job
          dockerfile: Dockerfile
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-cli-version: latest
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          path: .
          profile-name: default
          repo: auth
          region: ${AWS_REGION}
          registry-id: AWS_ECR_REGISTRY_ID
          tag: "${CIRCLE_WORKFLOW_ID}"
          push-image: true
          platform: linux/amd64
          requires:
            - test
      - aws-ecs/deploy-service-update:
          cluster: 'staging-demo'
          container-image-name-updates: 'container=auth-cont,tag=${CIRCLE_WORKFLOW_ID}'
          family: 'auth-new'
          service-name: 'auth-service'
          requires:
            - aws-ecr/build-and-push-image
          filters:
              branches:
                only: esc
      - aws-ecs/deploy-service-update:
          cluster: 'staging-demo'
          container-image-name-updates: 'container=auth-cont,tag=${CIRCLE_WORKFLOW_ID}'
          family: 'auth-new'
          service-name: 'auth-service'
          requires:
            - aws-ecr/build-and-push-image
          filters:
              branches:
                only: farid
