name: Build and Publish image to Docker Hub
on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build-worker-image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/blendluxcore-flamenco-ubuntu:2.8a1
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')  
          docker build ./Worker/ -t $IMAGE_ID
      - name: Push worker image to docker hub and login
        run: |
          echo ${{secrets.GITHUB_TOKEN}} | docker login -u ${{ github.repository_owner }} --password-stdin ghcr.io
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/blendluxcore-flamenco-ubuntu:2.8a1
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker push $IMAGE_ID