name: Build and Publish image to Docker Hub
on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build-image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/blendluxcore-headless-ubuntu:2.8a1
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')  
          docker build . -t $IMAGE_ID
      - name: Push image to docker hub and login
        run: |
          docker login -u ${{ github.repository_owner }} -p ${{secrets.GITHUB_TOKEN}} ghcr.io
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/blendluxcore-headless-ubuntu:2.8a1
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker push $IMAGE_ID