name: Build and Publish image to Docker Hub
on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build-image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/blendluxcore-headless-ubuntu:2.8a1
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')  
          docker build . -t $IMAGE_ID
#      - name: Log in to the Container registry
#        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
#        with:
#          registry: ${{ env.REGISTRY }}
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image to docker hub and login
        run: |
          echo ${{secrets.GITHUB_TOKEN}} | docker login -u ${{ github.repository_owner }} -p --password-stdin ghcr.io
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/blendluxcore-headless-ubuntu:2.8a1
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker push $IMAGE_ID
          echo hi
#      - name: Generate artifact attestation
#        uses: actions/attest-build-provenance@v2
#        with:
#          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
#          subject-digest: ${{ steps.push.outputs.digest }}
#          push-to-registry: true
#      - name: push image to docker hub
#        run: |
#          docker login -u thedoggo42 -p ${{secrets.DOCKER_HUB_TOKEN}}
#          docker push thedogg42/blendluxcore-headless-ubuntu:2.8a1