name: CI pipeline
on:
    workflow_dispatch:  
    pull_request:
      branches:
        - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        
        - uses: hadolint/hadolint-action@v3.1.0
          with:
            dockerfile: Dockerfile

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v6
